id = "yaml-nunjucks"
name = "YAML Nunjucks"
version = "0.1.2"
schema_version = 1
authors = ["Sebastian Forman <sebastian@forman.no>"]
description = "YAML with embedded Nunjucks template syntax support for .njk files"
repository = "https://github.com/sf0rman/yaml-nunjucks"

[grammars.yaml_nunjucks]
repository = "https://github.com/sf0rman/yaml-nunjucks.git"
rev = "1d72172fd4080f1ad978ad16c2548a89207a047d"
path = "grammars/tree-sitter-yaml-nunjucks"
